minimum_pre_commit_version: "4.0.0"

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check (auto-fix)
        entry: ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types_or: [python]
